### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by richardxy** [isarn/isarn-sketches-spark#16]
Hi,
I'm trying out this package, but consistently got this NoClassDefFoundError. 
I'm using Spark 2.3, Scala 2.11, and tested in Spark shell. My Python version is 3.7.
spark-shell  --jars /tmp/isarn-sketches-spark_2.11-0.3.1-sp2.3-py3.6.jar

scala> import org.isarnproject.sketches.udaf._, org.apache.spark.isarnproject.sketches.udt._
import org.isarnproject.sketches.udaf._
import org.apache.spark.isarnproject.sketches.udt._

scala>  val udaf = tdigestUDAF[Double]
java.lang.NoClassDefFoundError: org/isarnproject/sketches/TDigest$
  at org.isarnproject.sketches.udaf.package$.tdigestUDAF(package.scala:43)
  ... 53 elided
Caused by: java.lang.ClassNotFoundException: org.isarnproject.sketches.TDigest$
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 54 more

Would anyone be able to help? 
Thanks very much in advance!

Richard

**Comment by erikerlandson** [comment]
Looks like it is not finding the companion object `TDigest$`.  I've never tried it that way, but it may be a consequence of how spark loads `jar` files.

Out of curiosity, does this work for you:
```bash
spark-shell --packages "org.isarnproject::isarn-sketches-spark:0.3.1-sp2.3-py3.6"
```

**Comment by erikerlandson** [comment]
Also: `import org.isarnproject.sketches._`

**Comment by richardxy** [comment]
Thanks. I tried what you asked for

$spark-shell --packages "org.isarnproject:isarn-sketches-spark:0.3.1-sp2.3-py3.6"

Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.isarnproject#isarn-sketches-spark;0.3.1-sp2.3-py3.6: not found]

**Comment by richardxy** [comment]
What's your recommended way of loading the package?

**Comment by erikerlandson** [comment]
you need two colons after `org.isarnproject`

**Comment by richardxy** [comment]
$ spark-shell --packages "org.isarnproject::isarn-sketches-spark:0.3.1-sp2.3-py3.6"
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Provided Maven Coordinates must be in the form 'groupId:artifactId:version'. The coordinate provided is: org.isarnproject::isarn-sketches-spark:0.3.1-sp2.3-py3.6
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.deploy.SparkSubmitUtils$$anonfun$extractMavenCoordinates$1.apply(SparkSubmit.scala:1000)
        at org.apache.spark.deploy.SparkSubmitUtils$$anonfun$extractMavenCoordinates$1.apply(SparkSubmit.scala:998)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.deploy.SparkSubmitUtils$.extractMavenCoordinates(SparkSubmit.scala:998)
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1220)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:49)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:350)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:170)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by erikerlandson** [comment]
Oh, right it wants the scala version explicit.
```
spark-shell --packages "org.isarnproject:isarn-sketches-spark_2.11:0.3.1-sp2.3-py3.6"
```

I do think you'll also want: `import org.isarnproject.sketches._`

**Comment by richardxy** [comment]
Thanks. But... 

scala> import org.isarnproject.sketches._
import org.isarnproject.sketches._

scala> val udaf = tdigestUDAF[Double]
<console>:26: error: not found: value tdigestUDAF
       val udaf = tdigestUDAF[Double]

**Comment by erikerlandson** [comment]
ah, I meant "in addition to the other imports you already had"

**Comment by richardxy** [comment]
Got it. Thank you!

**Comment by erikerlandson** [comment]
I think originally, you might have just been missing the `import org.isarnproject.sketches._`, although I'm not sure if the `jar` file would have included all the right dependencies.

For maven style packages, the "intended" way is to use `--packages ...`, but if you got the full set of jar files for all deps, then `--jars` ought to work too

**Comment by richardxy** [comment]
I'll follow your suggestion of importing packages. I didn't know what's the right package name to use in the first place. Now I know. Thanks!
