### ISSUE TITLE
Unsafe Symbol TDigestSQL

### ISSUE THREAD

**Issue by richardxy** [isarn/isarn-sketches-spark#17]
Hi 

I was able to run my script in spark-shell, but when I submitted the job to run, it failed. The error message contains the following information:

`
Exception in thread "main" java.lang.AssertionError: assertion failed: unsafe symbol TDigestSQL (child of <none>) in runtime reflection universe
        at scala.reflect.internal.Symbols$Symbol.<init>(Symbols.scala:205)
        at scala.reflect.internal.Symbols$TypeSymbol.<init>(Symbols.scala:3030)
        at scala.reflect.internal.Symbols$ClassSymbol.<init>(Symbols.scala:3222)
        at scala.reflect.internal.Symbols$StubClassSymbol.<init>(Symbols.scala:3522)
        at scala.reflect.internal.Symbols$class.newStubSymbol(Symbols.scala:191)
        at scala.reflect.internal.SymbolTable.newStubSymbol(SymbolTable.scala:16)
        at scala.reflect.internal.Symbols$Symbol.newStubSymbol(Symbols.scala:521)
        at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:258)
        at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:286)
        at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:651)
        at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:419)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef$$anonfun$7.apply(UnPickler.scala:734)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef$$anonfun$7.apply(UnPickler.scala:734)
        at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:179)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.completeInternal(UnPickler.scala:734)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:761)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:195)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
        at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:195)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.info(SynchronizedSymbols.scala:195)
        at scala.reflect.internal.Symbols$SymbolContextApiImpl.typeSignature(Symbols.scala:160)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$typeSignature(SynchronizedSymbols.scala:195)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeSignature$1.apply(SynchronizedSymbols.scala:129)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeSignature$1.apply(SynchronizedSymbols.scala:129)
        at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
        at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:195)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.typeSignature(SynchronizedSymbols.scala:129)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.typeSignature(SynchronizedSymbols.scala:195)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.typeSignature(SynchronizedSymbols.scala:195)
        at org.apache.spark.sql.catalyst.ScalaReflection$$anonfun$getConstructorParameters$2.apply(ScalaReflection.scala:974)
        at org.apache.spark.sql.catalyst.ScalaReflection$$anonfun$getConstructorParameters$2.apply(ScalaReflection.scala:973)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at org.apache.spark.sql.catalyst.ScalaReflection$class.getConstructorParameters(ScalaReflection.scala:973)
        at org.apache.spark.sql.catalyst.ScalaReflection$.getConstructorParameters(ScalaReflection.scala:46)
        at org.apache.spark.sql.catalyst.ScalaReflection$$anonfun$org$apache$spark$sql$catalyst$ScalaReflection$$serializerFor$1.apply(ScalaReflection.scala:631)
        at org.apache.spark.sql.catalyst.ScalaReflection$$anonfun$org$apache$spark$sql$catalyst$ScalaReflection$$serializerFor$1.apply(ScalaReflection.scala:452)
        at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:56)
        at org.apache.spark.sql.catalyst.ScalaReflection$class.cleanUpReflectionObjects(ScalaReflection.scala:906)
        at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:46)
        at org.apache.spark.sql.catalyst.ScalaReflection$.org$apache$spark$sql$catalyst$ScalaReflection$$serializerFor(ScalaReflection.scala:452)
        at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:441)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(ExpressionEncoder.scala:71)
        at org.apache.spark.sql.Encoders$.product(Encoders.scala:275)
        at org.apache.spark.sql.LowPrioritySQLImplicits$class.newProductEncoder(SQLImplicits.scala:248)
        at org.apache.spark.sql.SQLImplicits.newProductEncoder(SQLImplicits.scala:34)
        at MultiTdigestToPostgres$.main(multi_feature_Tdigest.scala.scala:414)
        at MultiTdigestToPostgres.main(multi_feature_Tdigest.scala.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2018-12-13 18:22:46 INFO  SparkContext:54 - Invoking stop() from shutdown hook
`
Any clue of what had caused that? Any help would be greatly appreciated.

Richard

**Comment by richardxy** [comment]
Erik, 

When you get a chance, would you please look into this? I can provide further information about how I used TDigestSQL if needed. But mostly, I used TDigestSQL inside a Scala case class for "state", so that I can track multiple TDigestSQL objects within one state. 

Thanks!
Richard

**Comment by erikerlandson** [comment]
Hi @richardxy, is it possible to share code that reproduces this for me?  Also, when you say it didn't run when you submitted it, does that mean it runs using 'spark-shell' but not when submitted to a different cluster?

**Comment by richardxy** [comment]
Thank you Erik. Can I have your email so that I can send you the code?

**Comment by erikerlandson** [comment]
eje@redhat.com
or feel free to post it here

**Comment by richardxy** [comment]
Erik,

When I tested the code for the last time before I was ready to send you the code, and it worked, mysteriously. Just like a patient recovered himself before being sent to a doctor. I'll keep a close eye on it, but for now this ticket can be closed. I apologize for the false alarm. 

Thanks!

**Comment by erikerlandson** [comment]
glad it is working!   I'll close this, but we can re open it later if needed
